### ISSUE TITLE
Valeur par défaut pour formatBaguette

### ISSUE THREAD

**Issue by fedre30** [ouihelp/date-fns-baguette#1]
En testant la fonction `formatBaguette`, qui est très très utile pour Daca (merci beaucoup ! 🙏🏻) j'ai trouvé que ce serait utile d'avoir une valeur par défaut pour le `formatString` (ex. en ISO ce serait déjà très bien).
Des fois on veut juste comparer des dates et on n'a pas forcément besoin d'un formatage spécifique.

**Comment by b4stien** [comment]
Je close ici, pour comparer des dates on peut le faire directement sans passer par une string 👍.
